- hosts: w
  become: yes
  tasks:
    - name: Clean sealed
      file:
        path: "/lotus/worker/sealed/"
        state: absent

    - name: Clean unsealed
      file:
        path: "/lotus/worker/unsealed/"
        state: absent

    - name: Clean cache
      file:
        path: "/lotus/worker/cache/"
        state: absent
