- hosts: w
  become: yes
  tasks:
    - name: Clean old service
      file:
        path: "/usr/lib/systemd/system/{{ item }}"
        state: absent
      with_items:
        - lotus-w-a.service
        - lotus-w-p.service
        - lotus-w-c.service

    - name: Reload service
      ansible.builtin.systemd:
        daemon_reload: yes
