- hosts: w
  become: yes
  tasks:
    - name: Copy lotus-worker
      copy:
        src: /home/lo/fc/bin/lotus-worker
        dest: /home/lo/fc/bin/lotus-worker
        owner: "lo"
        group: "lo"
        mode: +x
