- hosts: n
  become: yes
  tasks:
    - name: Stop Miner
      systemd:
        name: lotus-miner
        state: stopped

    - name: Stop Node
      systemd:
        name: lotus-daemon
        state: stopped

    - name: Copy lotus
      copy:
        src: /home/lo/fc/bin/lotus
        dest: /home/lo/fc/bin/lotus
        owner: "lo"
        group: "lo"
        mode: +x

    - name: Copy lotus-miner
      copy:
        src: /home/lo/fc/bin/lotus-miner
        dest: /home/lo/fc/bin/lotus-miner
        owner: "lo"
        group: "lo"
        mode: +x

    - name: Start Node
      systemd:
        name: lotus-daemon
        state: started

    - name: Start Miner
      systemd:
        name: lotus-miner
        state: started
