- hosts: w
  become: yes
  tasks:
    - name: Copy GPU Driver
      copy:
        src: /home/lo/fc/NVIDIA-Linux-x86_64-460.91.03.run
        dest: /home/lo/fc/NVIDIA-Linux-x86_64.run
        owner: "lo"
        group: "lo"
        mode: +x

    - name: Install GPU Driver
      shell: /home/lo/fc/NVIDIA-Linux-x86_64.run -s

    - name: Clean GPU Driver
      file:
        path: "/home/lo/fc/NVIDIA-Linux-x86_64.run"
        state: absent
